DROP SCHEMA `jooq`;

CREATE DATABASE IF NOT EXISTS `jooq`
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

USE jooq;

DROP TABLE IF EXISTS POSTS;
CREATE TABLE POSTS (
  ID         INT(11)      NOT NULL AUTO_INCREMENT,
  TITLE      VARCHAR(200) NOT NULL,
  CONTENT    LONGTEXT              DEFAULT NULL,
  CREATED_ON DATETIME              DEFAULT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS (
  ID         INT(11)      NOT NULL AUTO_INCREMENT,
  POST_ID    INT(11)      NOT NULL,
  NAME       VARCHAR(200) NOT NULL,
  EMAIL      VARCHAR(200) NOT NULL,
  CONTENT    LONGTEXT              DEFAULT NULL,
  CREATED_ON DATETIME              DEFAULT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (POST_ID) REFERENCES POSTS (ID)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;